name: podlove_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  get: ^4.6.6
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  flutter_svg: ^2.0.16
  dotted_border: 2.1.0
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  pretty_dio_logger: ^1.4.0
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  pinput: ^5.0.1
  logger: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  flutter_html: ^3.0.0-beta.2
  zego_uikit_prebuilt_call: ^4.16.21
  webview_flutter: ^4.10.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  http_status_code: ^0.0.2
  awesome_snackbar_content: ^0.1.5
  phone_form_field: ^10.0.4
  floating: ^6.0.0
  intl_phone_field: ^3.2.0
  google_places_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/images/

  uses-material-design: true
