-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry
-dontwarn com.heytap.msp.push.**
-dontwarn com.huawei.hms.**
-dontwarn com.xiaomi.mipush.**
-dontwarn com.vivo.push.**
-dontwarn com.itgsa.opensdk.**
